Reproducible Research: HW1
==========================================

### Loading and preprocessing the data

```{r}
obj_csv <- read.csv("activity.csv")
obj_csv$date <- as.Date(obj_csv$date, format="%Y-%m-%d")
obj_clean <- na.omit(obj_csv)
```

### What is mean total number of steps taken per day?

```{r}
qplot(date, steps, data = obj_clean, stat="identity", geom = "histogram", width = 0.5)
```

```{r}
agr_steps <- aggregate(obj_clean$steps, list(Date = obj_clean$date), FUN = "sum")$x
mean(agr_steps)
median(agr_steps)
```

### What is the average daily activity pattern?

```{r}
avg <- aggregate(obj_clean$steps, list(interval = as.numeric(as.character(obj_clean$interval))), FUN = "mean")
qplot(interval, x, data = avg, stat="identity", geom = "line")
```

```{r}
avg[avg$x == max(avg$x),]
```

### Imputing missing values

```{r}
obj_csv2 <- obj_csv
for(i in 1:nrow(obj_csv2)){
	if(is.na(obj_csv2$steps[i])){
		obj_csv2$steps[i] <- avg[which(obj_csv2$interval[i] == avg$interval), ]$x
	}
}
```

```{r}
sum(is.na(obj_csv2))
qplot(date, steps, data = obj_csv2, stat="identity", geom = "histogram")
```

```{r}
agr_steps2 <- aggregate(obj_csv2$steps, list(Date = obj_csv2$date), FUN = "sum")$x
mean(agr_steps2)
median(agr_steps2)
```

```{r}
mean(agr_steps2) == mean(agr_steps)
```
```{r}
median(agr_steps2) == median(agr_steps)
```
```{r}
median(agr_steps2) - median(agr_steps)
```

### Are there differences in activity patterns between weekdays and weekends?

```{r}
obj_csv2$weekdays <- factor(format(obj_csv2$date, "%A"))
levels(obj_csv2$weekdays)
levels(obj_csv2$weekdays) <- list(weekday = c("周一", "周二", "周三", "周四", "周五"),
                                   weekend = c("周六", "周日"))
avg2 <- aggregate(obj_csv2$steps, list(interval = as.numeric(as.character(obj_csv2$interval)), weekdays = obj_csv2$weekdays), FUN = "mean")
```

```{r}
library(lattice)
xyplot(avg2$x ~ avg2$interval | avg2$weekdays, layout = c(1, 2), type = "l", xlab = "Interval", ylab = "Number of steps")
```



